/**
 * @file version.h
 * @brief 版本信息
 */
#ifndef OCRDETECT_COMMON_VERSION_H
#define OCRDETECT_COMMON_VERSION_H

#define OCRDETECT_VERSION_MAJOR 1
#define OCRDETECT_VERSION_MINOR 0
#define OCRDETECT_VERSION_PATCH 0
#define OCRDETECT_VERSION_STRING "1.0.0"

#endif /* OCRDETECT_COMMON_VERSION_H */
